export const GET_DEVICES_REQUEST = "GET_DEVICES_REQUEST";
export const GET_DEVICES_SUCCESS = "GET_DEVICES_SUCCESS";
export const GET_DEVICES_FAILURE = "GET_DEVICES_FAILURE";

export const GET_ADD_DEVICES_REQUEST = "GET_ADD_DEVICES_REQUEST";
export const GET_ADD_DEVICES_SUCCESS = "GET_ADD_DEVICES_SUCCESS";
export const GET_ADD_DEVICES_FAILURE = "GET_ADD_DEVICES_FAILURE";

export const GET_SINGLE_DEVICES_FAILURE = "GET_SINGLE_DEVICES_FAILURE";
export const GET_SINGLE_DEVICES_SUCCESS = "GET_SINGLE_DEVICES_SUCCESS";
export const GET_SINGLE_DEVICES_REQUEST = "GET_SINGLE_DEVICES_REQUEST";
